# Claude TTS Configuration File
# =============================
# Place in project root (.claude_tts.yml) or user home (~/.claude_tts/config.yml)
#
# Precedence (highest to lowest):
#   1. CLI arguments (always win)
#   2. Project root .claude_tts.yml
#   3. User home ~/.claude_tts/config.yml
#   4. Hardcoded defaults in script
#
# All values below are set to match the hardcoded defaults.
# Uncomment and modify values to customize behavior.

# Server configuration
server:
  # Kokoro-FastAPI server URL
  # Options: Any valid HTTP URL where Kokoro-FastAPI is running
  # Example: http://remote-server:8880 for remote server
  url: http://localhost:8880

# Audio settings
audio:
  # Voice to use. Available voices (67 total):
  #
  # American Female (af_): alloy, aoede, bella, heart, jadzia, jessica, kore,
  #   nicole, nova, river, sarah, sky, v0, v0bella, v0irulan, v0nicole, v0sarah, v0sky
  #
  # American Male (am_): adam, echo, eric, fenrir, liam, michael, onyx, puck,
  #   santa, v0adam, v0gurney, v0michael
  #
  # British Female (bf_): alice, emma, lily, v0emma, v0isabella
  #
  # British Male (bm_): daniel, fable, george, lewis, v0george, v0lewis
  #
  # Spanish (ef_/em_): dora, alex, santa
  #
  # French (ff_): siwis
  #
  # Hindi (hf_/hm_): alpha, beta, omega, psi
  #
  # Italian (if_/im_): sara, nicola
  #
  # Japanese (jf_/jm_): alpha, gongitsune, nezumi, tebukuro, kumo
  #
  # Portuguese (pf_/pm_): dora, alex, santa
  #
  # Chinese (zf_/zm_): xiaobei, xiaoni, xiaoxiao, xiaoyi, yunjian, yunxi, yunxia, yunyang
  #
  # Supports blending: "af_bella+af_sky" (equal) or "af_bella(2)+af_sky(1)" (weighted 2:1)
  voice: af_bella

  # Audio output format
  # Options: wav, mp3, pcm, opus, flac
  # Note: wav is most compatible with pygame, pcm is fastest for notifications
  format: wav

  # Speech speed multiplier
  # Range: 0.5 (slow) to 2.0 (fast)
  speed: 1.0

# Mode flags (all default to false)
# Set to true to enable by default

# Notification mode - optimized for Claude Code hooks (shorter timeouts, faster response)
notification: false

# Quiet mode - suppress non-error output
quiet: false

# Debug mode - enable debug logging with timing metrics
debug: false

# Streaming mode - enable streaming playback (requires PyAudio)
stream: false

# Background mode - play audio in background (non-blocking)
background: false

# Preload common messages at startup for instant playback
# Set to false to disable preloading (faster startup, slower first playback)
preload: true
